### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by IverCoder** [ethical-haquer/Thor_GUI#5]
### What happened?

When trying to run `Thor_GUI.py` after installing all the prerequisites, an error comes up.
Running `pip install pexpect sv-ttk tkinter-tooltip tkinterdnd2-universal` to install all prerequisites wield:
```
censored@censored:~$ pip install pexpect sv-ttk tkinter-tooltip tkinterdnd2-universal
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pexpect in /usr/lib/python3.12/site-packages (4.8.0)
Requirement already satisfied: sv-ttk in ./.local/lib/python3.12/site-packages (2.5.5)
Requirement already satisfied: tkinter-tooltip in ./.local/lib/python3.12/site-packages (2.1.0)
Requirement already satisfied: tkinterdnd2-universal in ./.local/lib/python3.12/site-packages (1.7.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/lib/python3.12/site-packages (from pexpect) (0.7.0)
```

### Thor GUI version

Alpha v0.4.2

### Thor Flash Utility version

1.0.4

### Thor GUI's log output

```shell
censored@censored:~$ python3 /var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py
/var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py:66: SyntaxWarning: invalid escape sequence '\ '
  ''')
Traceback (most recent call last):
  File "/var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py", line 19, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by ethical-haquer** [comment]
> ### What happened?
> 
> When trying to run `Thor_GUI.py` after installing all the prerequisites, an error comes up. Running `pip install pexpect sv-ttk tkinter-tooltip tkinterdnd2-universal` to install all prerequisites wield:
> 
> ```
> censored@censored:~$ pip install pexpect sv-ttk tkinter-tooltip tkinterdnd2-universal
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: pexpect in /usr/lib/python3.12/site-packages (4.8.0)
> Requirement already satisfied: sv-ttk in ./.local/lib/python3.12/site-packages (2.5.5)
> Requirement already satisfied: tkinter-tooltip in ./.local/lib/python3.12/site-packages (2.1.0)
> Requirement already satisfied: tkinterdnd2-universal in ./.local/lib/python3.12/site-packages (1.7.3)
> Requirement already satisfied: ptyprocess>=0.5 in /usr/lib/python3.12/site-packages (from pexpect) (0.7.0)
> ```
> 
> ### Thor GUI version
> 
> Alpha v0.4.2
> ### Thor Flash Utility version
> 
> 1.0.4
> ### Thor GUI's log output
> 
> ```shell
> censored@censored:~$ python3 /var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py
> /var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py:66: SyntaxWarning: invalid escape sequence '\ '
>   ''')
> Traceback (most recent call last):
>   File "/var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py", line 19, in <module>
>     import tkinter as tk
> ModuleNotFoundError: No module named 'tkinter'
> ```
> 
> ### Thor Flash Utility's log output
> 
> _No response_

Congrats on opening the very first Thor GUI issue! :slightly_smiling_face:

It looks like tkinter isn't installed on your system. Most systems include it with Python by default, but not in your case. 
What distro are you using? 
Thanks for reporting!

**Comment by ethical-haquer** [comment]
> ### What happened?
> 
> When trying to run `Thor_GUI.py` after installing all the prerequisites, an error comes up. Running `pip install pexpect sv-ttk tkinter-tooltip tkinterdnd2-universal` to install all prerequisites wield:
> 
> ```
> censored@censored:~$ pip install pexpect sv-ttk tkinter-tooltip tkinterdnd2-universal
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: pexpect in /usr/lib/python3.12/site-packages (4.8.0)
> Requirement already satisfied: sv-ttk in ./.local/lib/python3.12/site-packages (2.5.5)
> Requirement already satisfied: tkinter-tooltip in ./.local/lib/python3.12/site-packages (2.1.0)
> Requirement already satisfied: tkinterdnd2-universal in ./.local/lib/python3.12/site-packages (1.7.3)
> Requirement already satisfied: ptyprocess>=0.5 in /usr/lib/python3.12/site-packages (from pexpect) (0.7.0)
> ```
> 
> ### Thor GUI version
> 
> Alpha v0.4.2
> ### Thor Flash Utility version
> 
> 1.0.4
> ### Thor GUI's log output
> 
> ```shell
> censored@censored:~$ python3 /var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py
> /var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py:66: SyntaxWarning: invalid escape sequence '\ '
>   ''')
> Traceback (most recent call last):
>   File "/var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py", line 19, in <module>
>     import tkinter as tk
> ModuleNotFoundError: No module named 'tkinter'
> ```
> 
> ### Thor Flash Utility's log output
> 
> _No response_

According to [here](https://stackoverflow.com/a/25905642), this will install Tkinter:

For Ubuntu or other distros with Apt:

- sudo apt-get install python3-tk

For Fedora:

- sudo dnf install python3-tkinter

I have added this info to the README, sorry it took me so long! :blush:

**Comment by IverCoder** [comment]
> > ### What happened?
> > When trying to run `Thor_GUI.py` after installing all the prerequisites, an error comes up. Running `pip install pexpect sv-ttk tkinter-tooltip tkinterdnd2-universal` to install all prerequisites wield:
> > ```
> > censored@censored:~$ pip install pexpect sv-ttk tkinter-tooltip tkinterdnd2-universal
> > Defaulting to user installation because normal site-packages is not writeable
> > Requirement already satisfied: pexpect in /usr/lib/python3.12/site-packages (4.8.0)
> > Requirement already satisfied: sv-ttk in ./.local/lib/python3.12/site-packages (2.5.5)
> > Requirement already satisfied: tkinter-tooltip in ./.local/lib/python3.12/site-packages (2.1.0)
> > Requirement already satisfied: tkinterdnd2-universal in ./.local/lib/python3.12/site-packages (1.7.3)
> > Requirement already satisfied: ptyprocess>=0.5 in /usr/lib/python3.12/site-packages (from pexpect) (0.7.0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Thor GUI version
> > Alpha v0.4.2
> > ### Thor Flash Utility version
> > 1.0.4
> > ### Thor GUI's log output
> > ```shell
> > censored@censored:~$ python3 /var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py
> > /var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py:66: SyntaxWarning: invalid escape sequence '\ '
> >   ''')
> > Traceback (most recent call last):
> >   File "/var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py", line 19, in <module>
> >     import tkinter as tk
> > ModuleNotFoundError: No module named 'tkinter'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Thor Flash Utility's log output
> > _No response_
> 
> According to [here](https://stackoverflow.com/a/25905642), this will install Tkinter:
> 
> For Ubuntu or other distros with Apt:
> 
>     * sudo apt-get install python3-tk
> 
> 
> For Fedora:
> 
>     * sudo dnf install python3-tkinter
> 
> 
> I have added this info to the README, sorry it took me so long! 😊

Oh, sorry for not being able to respond for so long. I completely forgot about this since I just dual-booted to my Windows partition every time I had to flash anything via Odin 🥲 I'll try this again soon!

**Comment by ethical-haquer** [comment]
> > > ### What happened?
> > > When trying to run `Thor_GUI.py` after installing all the prerequisites, an error comes up. Running `pip install pexpect sv-ttk tkinter-tooltip tkinterdnd2-universal` to install all prerequisites wield:
> > > ```
> > > censored@censored:~$ pip install pexpect sv-ttk tkinter-tooltip tkinterdnd2-universal
> > > Defaulting to user installation because normal site-packages is not writeable
> > > Requirement already satisfied: pexpect in /usr/lib/python3.12/site-packages (4.8.0)
> > > Requirement already satisfied: sv-ttk in ./.local/lib/python3.12/site-packages (2.5.5)
> > > Requirement already satisfied: tkinter-tooltip in ./.local/lib/python3.12/site-packages (2.1.0)
> > > Requirement already satisfied: tkinterdnd2-universal in ./.local/lib/python3.12/site-packages (1.7.3)
> > > Requirement already satisfied: ptyprocess>=0.5 in /usr/lib/python3.12/site-packages (from pexpect) (0.7.0)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Thor GUI version
> > > Alpha v0.4.2
> > > ### Thor Flash Utility version
> > > 1.0.4
> > > ### Thor GUI's log output
> > > ```shell
> > > censored@censored:~$ python3 /var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py
> > > /var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py:66: SyntaxWarning: invalid escape sequence '\ '
> > >   ''')
> > > Traceback (most recent call last):
> > >   File "/var/home/censored/Downloads/thor-gui_linux_0.4.2-alpha/Thor_GUI.py", line 19, in <module>
> > >     import tkinter as tk
> > > ModuleNotFoundError: No module named 'tkinter'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Thor Flash Utility's log output
> > > _No response_
> > 
> > 
> > According to [here](https://stackoverflow.com/a/25905642), this will install Tkinter:
> > For Ubuntu or other distros with Apt:
> > ```
> > * sudo apt-get install python3-tk
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For Fedora:
> > ```
> > * sudo dnf install python3-tkinter
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have added this info to the README, sorry it took me so long! 😊
> 
> Oh, sorry for not being able to respond for so long. I completely forgot about this since I just dual-booted to my Windows partition every time I had to flash anything via Odin 🥲 I'll try this again soon!

No problem! I hope it works for you!
